// Generates docs/VECTORS.md from the red-team fixture.
//
// The page is generated rather than written because the claim it makes is a
// measurement. A hand-maintained list drifts from the fixture silently: someone
// adds a vector and the page still says 26, or a policy edit changes a reason
// string and the page keeps quoting the old one. Neither failure is visible to
// the person reading the page, which is the only person the page is for.
//
// So every number and every reason string here comes from evaluating the actual
// fixture against the actual starter policy with the engine the SDK ships. CI
// regenerates and fails on a diff, so a stale page cannot merge.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { LocalPolicyEngine } from "@11ai/execution-governance";

const VECTORS_PATH = "tests/vectors/injections.jsonl";
const POLICY_PATH = "tests/fixtures/starter-policy.yaml";
const OUT_PATH = "docs/VECTORS.md";
const GENERATOR = "scripts/gen-vectors-doc.ts";

interface Vector {
  tool: string;
  args: unknown;
  class: string;
  note: string;
}

interface Row extends Vector {
  id: string;
  decision: string;
  reason: string;
}

function read(path: string): string {
  try {
    return readFileSync(resolve(process.cwd(), path), "utf8");
  } catch (e) {
    throw new Error(
      `cannot read ${path} from ${process.cwd()}: ${(e as Error).message}. ` +
        `Run this from the repository root, via \`npm run gen:vectors\`.`,
    );
  }
}

/** Positional id: V01 is the first line of the fixture. */
function idFor(index: number, total: number): string {
  const width = Math.max(2, String(total).length);
  return "V" + String(index + 1).padStart(width, "0");
}

/** Markdown table cells cannot contain a bare pipe or a line break. */
function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

async function main(): Promise<void> {
  const vectors: Vector[] = read(VECTORS_PATH)
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .map((l, i) => {
      try {
        return JSON.parse(l) as Vector;
      } catch (e) {
        throw new Error(`${VECTORS_PATH} line ${i + 1} is not valid JSON: ${(e as Error).message}`);
      }
    });

  if (vectors.length === 0) throw new Error(`${VECTORS_PATH} contains no vectors`);

  const engine = new LocalPolicyEngine(resolve(process.cwd(), POLICY_PATH));
  const policyVersion = engine.version();

  const rows: Row[] = [];
  for (const [i, v] of vectors.entries()) {
    const result = await engine.evaluate({ sessionId: "vectors-doc", tool: v.tool, args: v.args });
    rows.push({
      ...v,
      id: idFor(i, vectors.length),
      decision: result.decision,
      reason: result.reason,
    });
  }

  const total = rows.length;
  const denied = rows.filter((r) => r.decision === "deny").length;

  // Class order follows first appearance in the fixture, so adding a vector
  // never reshuffles the sections above it.
  const classes: string[] = [];
  for (const r of rows) if (!classes.includes(r.class)) classes.push(r.class);

  const out: string[] = [];
  out.push(`<!-- Generated by ${GENERATOR}. Do not edit by hand.`);
  out.push(`     Source: ${VECTORS_PATH}`);
  out.push(`     Policy: ${POLICY_PATH}`);
  out.push(`     Regenerate with \`npm run gen:vectors\`. CI fails if this file is stale. -->`);
  out.push("");
  out.push("# Adversarial vectors");
  out.push("");
  out.push(
    `**${denied} of ${total} adversarial vectors are denied** under the starter policy, ` +
      `policy version \`${policyVersion}\`.`,
  );
  out.push("");
  out.push(
    `Every row below was produced by evaluating the vector against ` +
      `[\`${POLICY_PATH}\`](../${POLICY_PATH}) with the same local engine the SDK ships. ` +
      `The decision and reason columns are what the engine returned, not a description ` +
      `of what it is meant to return. The vectors themselves are in ` +
      `[\`${VECTORS_PATH}\`](../${VECTORS_PATH}), one JSON object per line.`,
  );
  out.push("");
  out.push(
    "Ids are positional: `V01` is the first line of the fixture. They stay stable as " +
      "long as vectors are appended rather than reordered.",
  );
  out.push("");
  if (denied !== total) {
    out.push(
      `> **${total - denied} vector(s) are not denied.** A vector in this set that is ` +
        `not denied is a hole in the starter policy, not an exception to document.`,
    );
    out.push("");
  }

  for (const cls of classes) {
    const inClass = rows.filter((r) => r.class === cls);
    out.push(`## ${cls} (${inClass.length})`);
    out.push("");
    out.push("| Id | What the agent attempts | Tool | Decision | Reason |");
    out.push("| --- | --- | --- | --- | --- |");
    for (const r of inClass) {
      out.push(
        `| ${r.id} | ${cell(r.note)} | \`${cell(r.tool)}\` | ${r.decision} | ${cell(r.reason)} |`,
      );
    }
    out.push("");
  }

  writeFileSync(resolve(process.cwd(), OUT_PATH), out.join("\n"));
  console.log(`${OUT_PATH}: ${total} vectors, ${denied} denied, policy ${policyVersion}`);
}

main().catch((e: unknown) => {
  console.error(`gen-vectors-doc: ${(e as Error).message}`);
  process.exit(1);
});
